name: CI
on: push

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: backend/go.mod
        cache-dependency-path: backend/go.sum
    - name: Test Backend
      working-directory: backend
      run: |
        go test -v ./...
    - name: Build Backend
      working-directory: backend
      run: |
        go build .

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache-dependency-path: frontend/package-lock.json
    - name: Install Dependencies
      working-directory: frontend
      run: |
        npm ci
    - name: Build Frontend
      working-directory: frontend
      run: |
        npm run prod
