name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Tag
      id: tags
      run: |
        cat <<EOF | sed "s@^@ghcr.io/${GITHUB_REPOSITORY,,}:@" | paste -sd, | sed 's/^/tags=/' >>"${GITHUB_OUTPUT}"
        latest
        ${TAG_NAME}
        EOF
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
    - uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.tags.outputs.tags }}
        push: true
